GET http://localhost:3000
###
GET http://localhost:3000/tampil
###
POST http://localhost:3000/tambah

###
DELETE http://localhost/delete

###

PUT http://localhost/ubah

### 
GET http://localhost:3000/tampilmatakuliah